/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Email": "邮箱",
    "Feedback": "反馈",
    "Games": "游戏",
    "Login": "登录",
    "Logout": "登出",
    "Password": "密码",
    "Register": "注册",
    "Don't have an account?": "还没有账号？",
    "About": "关于",
    "Confirm Password": "确认密码",
    "Name": "用户名",
    "Already have an account?": "已经有账号了？",
    "admin": "管理员",
    "Comments": "评论",
    "Endless": "无尽的RPG",
    "Featured Games": "推荐游戏",
    "Game ID: 2": "游戏ID: 2",
    "Game not found.": "游戏未找到。",
    "Jun 6, 04:02 AM": "6月6日04:02 AM",
    "Loading comments...": "加载评论...",
    "Loading game details...": "加载游戏细节...",
    "Loading games...": "加载游戏...",
    "Logging in...": "登录...",
    "No comments yet. Be the first to comment!": "目前还没有评论。第一个发表评论吧！",
    "Play Now": "立即开始",
    "Post": "帖子",
    "The best game you will ever encounter": "这是你遇到过的最棒的游戏",
    "Welcome": "欢迎",
    "Elemental Damage": "元素伤害",
    "EXP:": "经验值:",
    "Explore": "探索",
    "MAX": "最大",
    "Misc": "其它",
    "Quests": "任务",
    "Open Building Map": "打开建筑地图",
    "MISS": "未命中",
    "Offense": "进攻",
    "Rarity": "稀有度",
    "Rogue": "流氓",
    "Reset Attributes": "重置属性",
    "Reset All Progress": "重置所有进度",
    "Resources": "资源",
    "Stats": "属性",
    "Total Cost:": "总成本:",
    "Total Total Cost::": "总加成:",
    "Stop": "停止",
    "Normal Items": "普通物品",
    "Vampire": "吸血鬼",
    "Training": "训练",
    "NORMAL AMULET": "普通护身符",
    "Skill Tree": "技能树",
    "Soul Shop": "灵魂商店",
    "Saving...": "保存中...",
    "Salvage Item": "回收物品",
    "Salvage": "回收",
    "Progress:": "进度:",
    "First Blood": "第一滴血",
    "Gold (": "金币 (",
    "Gold bonus:": "金币加成:",
    "Highest Stage:": "最高关卡:",
    "Infinite Void": "无限虚空",
    "Inventory": "背包",
    "Items": "物品",
    "Kills": "击杀",
    "Level:": "等级:",
    "Life": "生命值",
    "Life Steal": "生命偷取",
    "Load from Cloud": "加载云存档",
    "Mana": "法力",
    "Mana Per Hit": "法力每击",
    "Massacre": "大屠杀",
    "Materials": "材料",
    "Max": "最大",
    "Mythic Items & Below": "神话物品及以下",
    "Magic Items & Below": "魔法物品及以下",
    "Rare Items & Below": "稀有物品及以下",
    "Auto Spell Cast": "自动施放法术",
    "先驱者": "战斗",
    "Harbinger": "先驱者",
    "Checking login...": "检查登录...",
    "Extra Life": "额外生命值",
    "Extra Material Drop %": "额外材料掉落 %",
    "Fight": "战斗",
    "Elementalist": "元素使",
    "Defense": "防御",
    "Crystal Cave": "水晶洞穴",
    "Crystal Shop": "水晶商店",
    "Current Level:": "当前等级:",
    "Arena": "竞技场",
    "Cloud Save Info:": "云存档信息:",
    "Buy": "购买",
    "Are you sure you want to overwrite your local save with this cloud save? This cannot be undone.": "您确定要用此云存档覆盖本地保存吗？这是无法挽回的。",
    "Total Bonus:": "总加成:",
    "Unlock Level:": "解锁等级:",
    "Universal Threat": "宇宙威胁",
    "Unique Items & Below": "独特物品及以下",
    "Warrior": "战士",
    "World Ender": "世界末日",
    "Save to Cloud": "保存到云存储",
    "Reset Skill Tree": "重置技能树",
    "Join our Discord": "加入我们的 Discord",
    "Extinction Event": "灭绝事件",
    "Holy warrior specializing in defense and vitality": "圣战士，专攻防御和活力",
    "Legendary Items & Below": "传说物品及以下",
    "Enchanted Forest": "魔法森林",
    "Swift and deadly, focusing on critical hits and attack speed": "迅速而致命，专注于暴击和攻击速度",
    "Progression": "进度",
    "Reality Breaker": "Reality Breaker",
    "Reset Arena Level": "重置竞技场等级",
    "Next Level Bonus:": "下一级加成:",
    "Bonus Skill Points": "奖励技能点",
    " multiplier on critical hits.": " 乘数当暴击时。",
    "Cosmic Terror": "宇宙恐怖",
    "Destroyer": "破坏者",
    "Element Strengths:": "元素力量:",
    "Effectiveness against enemy elements:": "对敌方元素的效果: ",
    "Death Incarnate": "死亡化身",
    "Frenzied fighter focusing on raw damage output": "狂热战士专注于原始伤害输出",
    "Master of elemental damage types": "精通元素伤害类型",
    "Master of life-stealing and critical strikes": "精通窃取生命和致命一击",
    "Material Drop bonus:": "材料掉落加成:",
    "No buildings constructed yet.": "暂无已建造的建筑物。",
    "Paladin": "圣骑士",
    "Percentage of damage dealt recovered as life.": "造成伤害的百分比恢复为生命。",
    "Refund all allocated attribute points": "退还所有已经分配的属性点",
    "Refund all skill points and reset path": "退还所有技能点并重置路径",
    "🌍 Mossback": "🌍 苔藓虫",
    "A mighty warrior specializing in heavy armor and raw strength": "精于重甲和原始力量的强大战士",
    "A shimmering cave filled with crystalized rocks.": "充满结晶岩石的闪闪发光的洞穴。",
    "Apocalypse": "启示录",
    "Auto-continue after death": "死亡后自动继续",
    "Automatically casts instant and buff skills": "自动施放即时和buff技能",
    "Berserker": "狂战士",
    "Continuous Play": "连续播放",
    "Current Bonuses:": "当前加成：",
    "Gain 1 resurrection per run": "每跑一次获得1点复活",
    "☁️ Sylvan Wisp": "☁️ 森林精灵",
    "🌍 Thornling": "🌍 荆棘",
    "Drag and drop an item here to salvage it.": "拖放一个物品到这里回收它。",
    "Sort materials": "材料排序",
    "Sorted materials by quantity, then id": "先按数量分类，再按编号分类",
    "☁️ Air → 🌍 Earth": "☁️ 气 → 🌍 土",
    "❄️ Cold → 🔥 Fire": "❄️ 冰 → 🔥 火",
    "🌍 Earth → ❄️ Cold": "🌍 土 → ❄️ 冰",
    "🔥 Fire → ☁️ Air": "🔥 火 → ☁️ 气",
    "🔥 Wildfire Spirit": "🔥 野火精灵",
    "Amount of life recovered per second.": "每秒恢复的生命量。",
    "Amount of mana recovered per second.": "每秒恢复的法力值。",
    "Are you sure you want to change to arena? That will reset your stage progress and will find you a new enemy": "你确定要换到竞技场吗？这将重置你的关卡进度，并为你找到一个新的敌人",
    "Base physical damage dealt to enemies.": "对敌人造成的基础物理伤害。",
    "Chance to block incoming attacks.": "有几率格挡来袭攻击。",
    "Chance to deal critical damage.": "有几率造成致命伤害。",
    "Critical Strike Chance": "暴击几率",
    "Critical Strike Damage": "暴击伤害",
    "Determines hit chance against enemies.": "决定对敌人的命中几率。",
    "Each point increases:": "每点增加：",
    "Effectiveness decreases in higher stages.": "在更高的阶段，效果会降低。",
    "Higher stages require more Attack Rating.": "更高的阶段需要更高的攻击等级。",
    "Increased by Strength and equipment.": "由力量和装备增加。",
    "Increased by Vitality and level ups.": "由活力和等级增加。",
    "Increased by Wisdom and level ups.": "由智慧和等级增加。",
    "Maximum life points.": "最大生命值。",
    "Maximum mana points.": "最大法力值。",
    "Number of attacks per second.": "每秒攻击次数。",
    "Reduces incoming damage.": "减少传入的伤害。",
    "🌍 Barkhide": "🌍 树皮怪",
    "Crystals": "水晶",
    "Souls": "灵魂",
    "Souls (": "灵魂 (",
    "Crystals (": "水晶 (",
    "Cost:": "成本:",
    "Claimed": "已领取",
    "Claim Reward": "领取奖励",
    "CritDamage": "暴击伤害",
    "CritChance": "暴击几率",
    "FireDamage": "火系伤害",
    "AirDamage": "气系伤害",
    "ColdDamage": "冰系伤害",
    "BlockChance": "格挡几率",
    "AttackSpeed": "攻击速度",
    "AttackRating": "攻击速率",
    "LifeSteal": "生命偷取",
    "LifeRegen": "生命回复",
    "ManaRegen": "法力回复",
    "Reach level 10 to select a class path!": "达到10级可选择职业路径！",
    "A mystical forest teeming with elemental creatures.": "一个充满自然生物的神秘森林。",
    "Explorer": "探险家",
    "First Steps": "第一步",
    "Experienced Fighter": "经验丰富的战士",
    "Master Hero": "英雄大师",
    "Midas Touch": "点石成金",
    "Millionaire": "百万富翁",
    "Pathfinder": "开拓者",
    "Reward:": "奖励:",
    "Rookie": "新手",
    "Voyager": "远航者",
    "Wanderer": "流浪者",
    "Ascended One": "转生一",
    "Big Hit": "大受打击",
    "Cataclysmic Blow": "灾难性的打击",
    "Category: Kills": "类别：击杀",
    "Category: Progression": "类别：进度",
    "Crystal Collector": "水晶收藏家",
    "Crystal Emperor": "水晶皇帝",
    "Crystal God": "水晶神",
    "Crystal Hoarder": "水晶囤积者",
    "Crystal Master": "水晶大师",
    "Crystal Merchant": "水晶商人",
    "Crystal Seeker": "寻晶者",
    "Devastating Strike": "毁灭性打击",
    "Dimensional Walker": "次元行者",
    "EarthDamage": "土系伤害",
    "Elite Champion": "精英冠军",
    "Epic Annihilator": "史诗歼灭者",
    "Epic Bane": "史诗之祸",
    "Epic Destroyer": "史诗破坏者",
    "Epic Slayer": "史诗杀手",
    "Epic Vanquisher": "史诗征服者",
    "Gold Baron": "黄金男爵",
    "Gold Hoarder": "黄金囤积者",
    "Golden Emperor": "黄金皇帝",
    "Infinite Wealth": "无限财富",
    "Legendary Being": "传说之人",
    "Legendary Conqueror": "传奇征服者",
    "Legendary Destroyer": "传说破坏者",
    "Legendary Hunter": "传说猎人",
    "Legendary Nightmare": "传说噩梦",
    "Legendary Slayer": "传奇杀手",
    "Mythic Apocalypse": "神话天启",
    "Mythic Bane": "神话克星",
    "Mythic Destroyer": "神话破坏者",
    "Mythic Hunter": "神话猎人",
    "Mythic Slayer": "神秘杀手",
    "Need 10 crystals for this upgrade": "这次升级需要10颗水晶",
    "Novice Adventurer": "新手冒险家",
    "Pocket Change": "零花钱",
    "Rare Apocalypse": "稀有天启",
    "Rare Exterminator": "稀有灭虫者",
    "Rare Hunter": "稀有猎人",
    "Rare Nemesis": "稀有克星",
    "Rare Specialist": "稀有专家",
    "Reality Hopper": "现实跳跃者",
    "Reality Shattering": "打破现实",
    "Rich Merchant": "富有的商人",
    "Seasoned Hero": "经验丰富的英雄",
    "Small Fortune": "小财富",
    "Transcendent": "超凡脱俗",
    "Treasure God": "宝神",
    "Treasure Tycoon": "宝藏大亨",
    "Veteran Warrior": "经验丰富的战士",
    "Wealthy Adventurer": "富有的冒险家",
    "World Traveler": "环球旅行家",
    "BLOCKED": "格挡",
    "Earned from killing monsters.": "通过杀死怪物获得。",
    "Not enough souls!": "没有足够的灵魂！",
    "Gold": "金币",
    "Category: Rarity": "类别: 稀有度",
    "Category: Resources": "类别: 资源",
    "NORMAL PANTS": "普通裤子",
    "Not enough souls!": "没有足够的灵魂！",
    "Used to buy upgrades.": "用于购买升级。",
    "Rare currency for powerful upgrades and skill resets.": "用于强大升级和技能重置的稀有货币。",
    "Not logged in": "未登录",
    "Log in": "登录",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "© 2025 GT Platform. All rights reserved.": "© 2025 GT Platform. All rights reserved.",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "What's up, ": "怎么了，",
    "Earth Damage: ": "土系伤害: ",
    "Elemental Damage: ": "元素伤害: ",
    "Stage: ": "关卡: ",
    "Total Time In Fights: ": "战斗总时长: ",
    "Bonus Experience": "奖励经验",
    "Extra Material Drop Chance": "额外材料掉落几率",
    "Extra Material Drop Max": "额外材料掉落上限",
    "Bonus Gold": "奖励金币",
    "Crit Chance": "暴击几率",
    "Crit Damage": "暴击伤害",
    "Damage Boost": "伤害提升",
    "Attack Rating": "攻击速率",
    "Attack Speed": "攻击速度",
    "Cold Damage": "冰系伤害",
    "Earth Damage": "土系伤害",
    "Fire Damage": "火系伤害",
    "Air Damage": "气系伤害",
    "Mana Boost": "法力提升",
    "Life Boost": "生命提升",
    "Life Steal": "生命偷取",
    "Life Steal: ": "生命偷取: ",
    "Life: ": "生命值: ",
    "Agility": "敏捷",
    "Cold Damage: ": "冰系伤害: ",
    "Earth Damage: ": "土系伤害: ",
    "Fire Damage: ": "火系伤害: ",
    "Air Damage: ": "气系伤害: ",
    "Armor": "护甲",
    "Current Bonus:": "当前加成:",
    "Attributes (": "属性 (",
    "Highest Damage Dealt: ": "造成的最高伤害: ",
    "Block Chance": "格挡几率",
    "Attack Speed": "攻击速度",
    "Damage": "伤害",
    "Crystals: ": "水晶: ",
    "Gold: ": "金币: ",
    "Level: ": "等级: ",
    "Souls: ": "灵魂: ",
    "Vitality": "活力",
    "Total Time Played: ": "总游戏时长: ",
    "Total Items Found: ": "总计发现的物品: ",
    "Total Souls Earned: ": "总计赚取的灵魂: ",
    "Total Gold Earned: ": "总计赚取的金币: ",
    "Total Crystals Earned: ": "总计赚取的水晶: ",
    "Total Enemies Killed: ": "总计击杀的敌人: ",
    "Starting Stage": "开始关卡",
    "Highest Stage Reached: ": "达到的最高关卡: ",
    "Last save: ": "最近保存: ",
    "(Equipped) ": "(已装备) ",
    "Dexterity": "灵巧",
    "Endurance": "耐力",
    "Strength": "力量",
    "Maximum: ": "最大: ",
    "Bosses Defeated: ": "击败的Boss: ",
    "Reset Arena Level to ": "重置竞技场等级为 ",
    "Reset Arena level to ": "重置竞技场等级为 ",
    "Increases starting stage by ": "增加初始关卡 ",
    "LEVEL UP! ": "升级! ",
    "Wisdom": "智慧",
    "Last cloud save: ": "最近一次云存储 ",
    "Mana (Lvl ": "法力 (等级 ",
    "Life (Lvl ": "生命值 (等级 ",
    "Life Regeneration": "生命回复",
    "Mana Regeneration": "法力回复",
    "Quest \"": "任务 \"",
    "Found: ": "发现: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/sec)": "/秒)",
    "% bonus": "% 奖励",
    " day(s)": " 天",
    "% damage vs same element": "% 伤害对同一元素",
    "% damage vs opposite element": "% 伤害对相反元素",
    "% damage vs other elements": "% 伤害对其它元素",
    "\" claimed!": "\" 奖励已领取!",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^: \+([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^: \+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Upgraded Life Steal by (.+) levels!$/, '你把 生命偷取 升级了 $1 级！'],
    [/^Upgraded Armor by (.+) levels!$/, '你把 护甲 升级了 $1 级！'],
    [/^Upgraded Damage by (.+) levels!$/, '你把 伤害 升级了 $1 级！'],
    [/^Upgraded Earth Damage by (.+) levels!$/, '你把 土系伤害 升级了 $1 级！'],
    [/^Upgraded Crit Damage by (.+) levels!$/, '你把 暴击伤害 升级了 $1 级！'],
    [/^Upgraded Attack Rating by (.+) levels!$/, '你把 攻击速率 升级了 $1 级！'],
    [/^Upgraded Attack Speed by (.+) levels!$/, '你把 攻击速度 升级了 $1 级！'],
    [/^Upgraded Block Chance by (.+) levels!$/, '你把 格挡几率 升级了 $1 级！'],
    [/^Upgraded Crit Chance by (.+) levels!$/, '你把 暴击几率 升级了 $1 级！'],
    [/^Upgraded Air Damage by (.+) levels!$/, '你把 气系伤害 升级了 $1 级！'],
    [/^Upgraded Cold Damage by (.+) levels!$/, '你把 冰系伤害 升级了 $1 级！'],
    [/^Upgraded Fire Damage by (.+) levels!$/, '你把 火系伤害 升级了 $1 级！'],
    [/^Upgraded Mana by (.+) levels!$/, '你把 法力 升级了 $1 级！'],
    [/^Upgraded Life by (.+) levels!$/, '你把 生命值 升级了 $1 级！'],
    [/^Upgraded Life Regeneration by (.+) levels!$/, '你把 生命值回复 升级了 $1 级！'],
    [/^Upgraded Mana Regeneration by (.+) levels!$/, '你把 法力回复 升级了 $1 级！'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Salvaged (.+) normal or lower items, gained (.+) gold$/, '回收 $1 件普通或更低的物品，获得 $2 金币'],
    [/^Earn a total of (.+) gold.$/, '总计赚取 $1 金币。'],
    [/^Earn a total of (.+) crystals.$/, '总计赚取 $1 水晶。'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^• Critical Damage by ([\d\.]+)$/, '• 暴击伤害 $1'],
    [/^• Attack Rating by ([\d\.]+)$/, '• 攻击速率 $1'],
    [/^• Armor by ([\d\.]+)$/, '• 护甲 $1'],
    [/^• Damage by ([\d\.]+)$/, '• 伤害 $1'],
    [/^• Life by ([\d\.]+)$/, '• 生命值 $1'],
    [/^• Mana by ([\d\.]+)$/, '• 法力 $1'],
    [/^\+([\d\.]+)\% Extra Material Drop Chance$/, '\+$1\% 额外材料掉落几率'],
    [/^\+([\d\.]+)\% Damage Boost$/, '\+$1\% 伤害提升'],
    [/^\+([\d\.]+)\% Life Boost$/, '\+$1\% 生命提升'],
    [/^\+([\d\.]+)\% Mana Boost$/, '\+$1\% 法力提升'],
    [/^\+([\d\.]+)\% Bonus Gold$/, '\+$1\% 奖励金币'],
    [/^\+([\d\.]+)\% Bonus Experience$/, '\+$1\% 奖励经验值'],
    [/^\+([\d\.]+) souls\/min$/, '\+$1 灵魂\/分钟'],
    [/^\+([\d\.]+) crystals\/min$/, '\+$1 水晶\/分钟'],
    [/^\+([\d\.]+) gold\/min$/, '\+$1 金币\/分钟'],
    [/^\+([\d\.]+) Life Steal$/, '\+$1 生命偷取'],
    [/^\+([\d\.]+) Damage$/, '\+$1 伤害'],
    [/^\+([\d\.]+) Extra Material Drop Max$/, '\+$1 额外材料掉落上限'],
    [/^\+([\d\.]+) Mana Boost$/, '\+$1 法力提升'],
    [/^\+([\d\.]+) Life Boost$/, '\+$1 生命提升'],
    [/^\+([\d\.]+) Damage Boost$/, '\+$1 伤害提升'],
    [/^\+([\d\.]+) Bonus Gold$/, '\+$1 奖励的金币'],
    [/^\+([\d\.]+) Attack Speed$/, '\+$1 攻击速度'],
    [/^\+([\d\.]+) Bonus Experience$/, '\+$1 奖励的经验值'],
    [/^\+([\d\.]+) Crit Chance$/, '\+$1 暴击几率'],
    [/^\+([\d\.]+) Crit Damage$/, '\+$1 暴击伤害'],
    [/^\+([\d\.]+) Air Damage$/, '\+$1 气系 伤害'],
    [/^\+([\d\.]+) Cold Damage$/, '\+$1 冰系 伤害'],
    [/^\+([\d\.]+) Earth Damage$/, '\+$1 土系 伤害'],
    [/^\+([\d\.]+) Fire Damage$/, '\+$1 火系 伤害'],
    [/^\+([\d\.]+) Attack Rating$/, '\+$1 攻击速率'],
    [/^\+([\d\.]+) Block Chance$/, '\+$1 格挡几率'],
    [/^\+([\d\.]+) Mana Regeneration$/, '\+$1 法力回复'],
    [/^\+([\d\.]+) Life Regeneration$/, '\+$1 生命回复'],
    [/^\+([\d\.]+) Extra Material Drop Chance$/, '\+$1 额外材料掉落几率'],
    [/^\+([\d\.]+) Extra Material Drop Max$/, '\+$1 额外材料掉落上限'],
    [/^\+([\d\.]+) Armor$/, '\+$1 护甲'],
    [/^\+([\d\.]+) Mana$/, '\+$1 法力'],
    [/^\+([\d\.]+) Life$/, '\+$1 生命值'],
    [/^\+([\d\.]+) Starting Stage$/, '\+$1 初始关卡'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/, '$1小时 $2分 $3秒'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^ \(Lvl ([\d\.,]+)\)$/, ' (等级 $1)'],
    [/^([\d\.,]+) Souls$/, '$1 灵魂'],
    [/^([\d\.,]+) Crystals$/, '$1 水晶'],
    [/^([\d\.,]+) attacks\/second$/, '$1 攻击/秒'],
    [/^([\d\.,]+) Gold$/, '$1 金币'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) characters left$/, '剩余 $1 字符'],
    [/^Requires Level ([\d\.,]+)$/, '要求等级 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Deal ([\d\.,]+) damage in a single hit.$/, '在一次攻击中造成 $1 伤害。'],
    [/^Reach level ([\d\.,]+).$/, '达到等级 $1。'],
    [/^Reach stage ([\d\.,]+).$/, '达到关卡 $1。'],
    [/^Defeat ([\d\.,]+) mythic enemies.$/, '击败 $1 神话 敌人。'],
    [/^Defeat ([\d\.,]+) epic enemies.$/, '击败 $1 史诗 敌人。'],
    [/^Defeat ([\d\.,]+) rare enemies.$/, '击败 $1 稀有 敌人。'],
    [/^Defeat ([\d\.,]+) legendary enemies.$/, '击败 $1 传说 敌人。'],
    [/^Defeat ([\d\.,]+) legendary enemie.$/, '击败 $1 传说 敌人。'],
    [/^Defeat ([\d\.,]+) mythic enemie.$/, '击败 $1 神话 敌人。'],
    [/^Defeat ([\d\.,]+) epic enemie.$/, '击败 $1 史诗 敌人。'],
    [/^Defeat ([\d\.,]+) rare enemie.$/, '击败 $1 稀有 敌人。'],
    [/^Defeat ([\d\.,]+) enemies.$/, '击败 $1 敌人。'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Base: (.+) damage$/, '基础：$1 伤害'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);